### ISSUE TITLE
Limit on the number of characters?

### ISSUE THREAD

**Issue by Broccoli-nyu** [Stewart-Anubis/Chat-Hud-Countdown-Translator-Anubis-Edition#1]
For example, take this map. As you can see in the screenshot, the Russian text is not fully displayed by the plugin. At the same time, when I write the same text in the chat myself, it is fully visible. As you can see in the second screenshot from the map config, the Russian translation is a few characters smaller.

I would be very grateful if you could fix that. Or tell me how to fix it, if it's possible to fix it without updating this plugin.

And yes, thank you very much for such a useful plugin

![csgo_2021-04-15_21-45-50](https://user-images.githubusercontent.com/38692648/114995239-48ea3380-9ea6-11eb-9402-d667ba53d835.png)

![notepad++_2021-04-16_11-26-47](https://user-images.githubusercontent.com/38692648/114995946-037a3600-9ea7-11eb-8c8c-22483b31e8b2.png)

**Comment by Stewart-Anubis** [comment]
#define MAXLENGTH_INPUT 		128
for 
#define MAXLENGTH_INPUT 		256

I increased the number of characters in the chat. If you want to increase more, don't increase it too much by bursting the memory.

**Comment by Broccoli-nyu** [comment]
> #define MAXLENGTH_INPUT 128
> for
> #define MAXLENGTH_INPUT 256
> 
> I increased the number of characters in the chat. If you want to increase more, don't increase it too much by bursting the memory.

Thank you so much <3
