### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Truyn** [Stewart-Anubis/Chat-Hud-Countdown-Translator-Anubis-Edition#3]
I have ru server and ru client but I don't see the translation

**Comment by Stewart-Anubis** [comment]
There are two versions. The official and the beta.
You must only use one of them. The official "chat_hud.smx" Generates the files in the folder “configs/Chat_Hud/map.txt” according to which the map is generating and showing the messages, and after generating these files with the map reset, you have to translate these files for the language you want to be shown, to be shown the next time the map is played on the server. The beta version "chat_hud_beta.smx" uses the google translations API to generate the already translated files, it considers the base language of the server configured in "configs/core.cfg" "ServerLang" "ru" as a base. This will only work if the following cvars are added to "bspconvar_whitelist.txt".

	say													1
	exec												1
	sm_cvar												1
	sm_say												1
	zr_infect_mzombie_ratio								1
	zr_infect_mzombie_respawn							1
	zr_infect_spawntime_max								1
	zr_infect_spawntime_min								1
	zr_roundend_overlay									1
	zr_roundend_overlays_zombie							1
	zr_roundend_overlays_human							1
	zr_ambientsounds_volume								1
	zr_respawn											1
	zr_respawn_delay									1
	zr_respawn_team_zombie								1
	zr_respawn_team_zombie_world						1
	zr_class_modify										1
	zr_roundend_overlays_zombie							1
	zr_roundend_overlays_human							1
	sm_gravity											1

**Comment by Truyn** [comment]
thx!
